name = "rss--trigger-pm"
main = "src/index.js"
compatibility_date = "2024-11-25"

[triggers]
# Run daily at 15:00 GMT
crons = ["0 15 * * *"]

[vars]
RSS_ENDPOINT = "https://hooks.jonathan-harris.online/x20n0wzcy7t5s0"
