name = "rsstrigger"
main = "src/index.js"
compatibility_date = "2025-11-25"

[triggers]
# Run daily at 15:00 GMT
crons = ["15 * * *"]

[vars]
RSS_ENDPOINT = "https://hooks.jonathan-harris.online/x20n0wzcy7t5s0"
